### ISSUE TITLE
Testimonials - Could we remove the featured images here?

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Cavalier-Portable-Homes#57]
Requested by Calvin Bishop

**Comment by ravi-josyula** [comment]
Please remove the default no image as well.
![testimonials - cavalier portable homes 2016-02-10 11-08-08](https://cloud.githubusercontent.com/assets/13309806/12939590/002c9548-cf76-11e5-89d7-2c2044d76bd3.png)
